<%
require 'yaml'

formula = YAML.load_file('FORMULA')
formula_name = formula['name']
%>
---
verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-9
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd
      image: saltstack/centos-7-minimal

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  salt_pillar_root: pillar.example
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: <%= formula_name %>
  state_top:
    base:
      '*':
        - <%= formula_name %>

suites:
  - name: default
