<%
require 'yaml'

formula = YAML.load_file('FORMULA')
formula_name = formula['name']
%>
---
driver:
  name: vagrant

platforms:
  - name: centos-7.3

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: mysql
  state_top:
    base:
      '*':
        - mysql
  pillars:
    top.sls:
      base:
        '*':
          - mysql

suites:
  - name: default
    provisioner:
      pillars-from-files:
        mysql.sls: pillar.extenda
